# Generated by Django 4.1.3 on 2023-03-24 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_booking_options_alter_room_options_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
    ]
